# Generated by Django 4.0 on 2022-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemapapp', '0002_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
