# Generated by Django 4.0 on 2022-04-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemapapp', '0005_remove_person_age_remove_person_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
