# Generated by Django 4.0 on 2022-04-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemapapp', '0007_group_parent_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.AddField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Group', to='sitemapapp.person'),
        ),
    ]
