# Generated by Django 4.0 on 2022-04-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemapapp', '0008_remove_group_parent_person_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parent',
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemapapp.group'),
        ),
    ]
